<?php
/**
 * Image manifest. GENERATED by the build script, do not hand-edit.
 * Gives every image its intrinsic size so <img> can carry width/height
 * and the browser reserves space before the file loads (no layout shift).
 */
return [
    'brand/menu-flyer' => ['w' => 1054, 'h' => 1492, 'sizes' => [480, 800]],
    'photos/aerial-property' => ['w' => 1600, 'h' => 900, 'sizes' => [480, 800, 1200]],
    'photos/bathroom' => ['w' => 1269, 'h' => 1239, 'sizes' => [480, 800, 1200]],
    'photos/breakfast-service' => ['w' => 1086, 'h' => 1448, 'sizes' => [480, 800]],
    'photos/cosy-bar' => ['w' => 1536, 'h' => 1024, 'sizes' => [480, 800, 1200]],
    'photos/courtyard' => ['w' => 1536, 'h' => 1024, 'sizes' => [480, 800, 1200]],
    'photos/dining-table' => ['w' => 1280, 'h' => 960, 'sizes' => [480, 800, 1200]],
    'photos/entrance' => ['w' => 1600, 'h' => 900, 'sizes' => [480, 800, 1200]],
    'photos/exterior-gate' => ['w' => 1600, 'h' => 899, 'sizes' => [480, 800, 1200]],
    'photos/lounge' => ['w' => 1536, 'h' => 1024, 'sizes' => [480, 800, 1200]],
    'photos/room-deluxe' => ['w' => 1448, 'h' => 1086, 'sizes' => [480, 800, 1200]],
    'photos/room-executive' => ['w' => 1536, 'h' => 1024, 'sizes' => [480, 800, 1200]],
    'photos/team' => ['w' => 1536, 'h' => 1024, 'sizes' => [480, 800, 1200]],
    'stock/attraction-entebbe-gardens' => ['w' => 1920, 'h' => 1440, 'sizes' => [480, 800, 1200, 1920]],
    'stock/attraction-kampala' => ['w' => 1920, 'h' => 1440, 'sizes' => [480, 800, 1200, 1920]],
    'stock/attraction-lake-victoria' => ['w' => 1920, 'h' => 1280, 'sizes' => [480, 800, 1200, 1920]],
    'stock/attraction-mabira' => ['w' => 1920, 'h' => 1440, 'sizes' => [480, 800, 1200, 1920]],
    'stock/attraction-namugongo' => ['w' => 1920, 'h' => 1440, 'sizes' => [480, 800, 1200, 1920]],
    'stock/attraction-ssezibwa-falls' => ['w' => 1920, 'h' => 1439, 'sizes' => [480, 800, 1200, 1920]],
    'stock/drink-coffee' => ['w' => 1600, 'h' => 2400, 'sizes' => [480, 800, 1200]],
    'stock/drink-juice' => ['w' => 1600, 'h' => 900, 'sizes' => [480, 800, 1200]],
    'stock/food-chicken' => ['w' => 1600, 'h' => 2399, 'sizes' => [480, 800, 1200]],
    'stock/food-chicken-greens' => ['w' => 1600, 'h' => 2399, 'sizes' => [480, 800, 1200]],
    'stock/food-fish' => ['w' => 1600, 'h' => 1068, 'sizes' => [480, 800, 1200]],
    'stock/food-fish-whole' => ['w' => 1600, 'h' => 1067, 'sizes' => [480, 800, 1200]],
];
